name: Backend Linters

on: pull_request

env:
  FORCE_COLOR: 1

defaults:
  run:
    working-directory: backend

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x
      - name: Setup Rubocop
        run: |
          gem install --no-document rubocop:'~>1.12' 
          gem install --no-document rubocop-performance:'~>1.11.0'
          gem install --no-document rubocop-rails:'~>2.9.1'
          gem install --no-document rubocop-thread_safety:'~>0.4.2'
          gem install --no-document rubocop-rspec:'~>2.3.0'
          [ -f .rubocop.yml ]
      - name: Rubocop Report
        run: rubocop --color
