name: Tests

on: pull_request

jobs:
  test-frontend:
    env:
      WORKING_DIRECTORY: ./frontend
      CI: "true"
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install NPM Packages (Global)
        run: yarn install

      - name: Install NPM Packages
        run: yarn install
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Lint
        run: yarn ts-standard
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Jest
        run: yarn test --coverage --ci
        working-directory: ${{env.WORKING_DIRECTORY}}

  tests-backend:
    env:
      WORKING_DIRECTORY: ./backend
      RAILS_ENV: test
      CI: "true"
      DATABASE_URL: postgres://postgres:postgres@localhost/backend_test
    name: Rspec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: backend_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Setup test database
        run: bin/rails db:schema:load
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Run tests
        run: bundle exec rspec
        working-directory: ${{env.WORKING_DIRECTORY}}

  tests-cypress:
    env:
      RAILS_ENV: test
      CI: "true"
      DATABASE_URL: postgres://postgres:postgres@localhost/backend_test
    name: Cypress
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: backend_test
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install NPM Packages (Global)
        run: yarn install

      - name: Install NPM Packages (Global)
        run: yarn install

      - name: Install NPM Packages (E2E)
        run: yarn install
        working-directory: e2e_tests

      - name: Install NPM Packages (Frontend)
        run: yarn install
        working-directory: frontend

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./backend

      - name: Setup test database
        run: bin/rails db:schema:load
        working-directory: ./backend

      - name: Run test server
        run: bundle exec rails s &
        working-directory: ./backend

      - name: Run frontend server
        run: yarn start &
        working-directory: ./frontend

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./e2e_tests
          install: true
          wait-on: "http://localhost:3001"
          wait-on-timeout: 120
          browser: chrome
          headless: true
          spec: cypress/integration/application/**/*.spec.ts
